// 자동 생성: scripts/gen_brand_domains_dart.py
// data/*.csv 의 brand_ko/brand_en -> brand_domain (+ALIASES).
// 로고 렌더링용. 빈 도메인 브랜드는 여기 없음(BrandLogo 가 폴백 처리).
// 갱신: CSV 수정 후 이 스크립트 재실행.

const Map<String, String> brandDomains = {
  '8SECONDS': 'ssfshop.com',
  'A Twosome Place': 'twosome.co.kr',
  'ASICS': 'asics.com',
  'Angel-in-us': 'angelinus.com',
  'BLACKYAK': 'blackyak.com',
  'Birkenstock': 'birkenstock.com',
  'Burger King': 'burgerking.com',
  'Compose Coffee': 'composecoffee.com',
  'Converse': 'converse.com',
  'Covernat': 'covernat.net',
  'Crocs': 'crocs.com',
  'DESCENTE': 'descente.com',
  'Discovery': 'discovery-expedition.com',
  'Dr. Martens': 'drmartens.com',
  'EDIYA': 'ediya.com',
  'Emart': 'emart.com',
  'Gong cha': 'gong-cha.com',
  'HOKA': 'hoka.com',
  'HOLLYS': 'hollys.com',
  'Harim': 'harim.com',
  'IMVELY': 'imvely.com',
  'K2': 'k2.co.kr',
  'KOLON SPORT': 'kolonsport.com',
  'Kumkang': 'kumkang.com',
  'Kyochon': 'kyochon.com',
  'Lotteria': 'lotteria.com',
  'MFDS': 'mfds.go.kr',
  'MUSINSA STANDARD': 'musinsa.com',
  'McDonald\'s': 'mcdonalds.com',
  'NEPA': 'nepa.co.kr',
  'New Balance': 'newbalance.com',
  'Nike': 'nike.com',
  'Nongshim': 'nongshim.com',
  'Ottogi': 'ottogi.co.kr',
  'PRO-SPECS': 'prospecs.com',
  'PUMA': 'puma.com',
  'Paik\'s Coffee': 'paikdabang.com',
  'Paldo': 'paldofood.co.kr',
  'Paqui': 'paqui.com',
  'Paul Bassett': 'paulbassett.co.kr',
  'SPAO': 'spao.com',
  'Salomon': 'salomon.com',
  'Samyang': 'samyangfoods.com',
  'Smoothie King': 'smoothieking.com',
  'Starbucks': 'starbucks.com',
  'TOM N TOMS': 'tomntoms.com',
  'TOPTEN10': 'topten.shinsung.co.kr',
  'The Coffee Bean': 'coffeebeankorea.com',
  'The Liter': 'theliter.com',
  'The North Face': 'thenorthface.com',
  'The Venti': 'theventi.co.kr',
  'Tim Hortons': 'timhortons.com',
  'UNIQLO': 'uniqlo.com',
  'Vans': 'vans.com',
  'Wilson Korea': 'wilson.com',
  'Yupdduk': 'yupdduk.com',
  'ZARA': 'zara.com',
  'adidas': 'adidas.com',
  'thisisneverthat': 'thisisneverthat.com',
  '공차': 'gong-cha.com',
  '교촌': 'kyochon.com',
  '금강제화': 'kumkang.com',
  '나이키': 'nike.com',
  '네파': 'nepa.co.kr',
  '노스페이스': 'thenorthface.com',
  '농심': 'nongshim.com',
  '뉴발란스': 'newbalance.com',
  '닥터마틴': 'drmartens.com',
  '더리터': 'theliter.com',
  '더벤티': 'theventi.co.kr',
  '데상트': 'descente.com',
  '디스이즈네버댓': 'thisisneverthat.com',
  '롯데리아': 'lotteria.com',
  '맥도날드': 'mcdonalds.com',
  '무신사 스탠다드': 'musinsa.com',
  '반스': 'vans.com',
  '버거킹': 'burgerking.com',
  '버켄스탁': 'birkenstock.com',
  '블랙야크': 'blackyak.com',
  '빽다방': 'paikdabang.com',
  '살로몬': 'salomon.com',
  '삼양식품': 'samyangfoods.com',
  '스무디킹': 'smoothieking.com',
  '스타벅스': 'starbucks.com',
  '스파오': 'spao.com',
  '식약처': 'mfds.go.kr',
  '식약처 기준': 'mfds.go.kr',
  '아디다스': 'adidas.com',
  '아식스': 'asics.com',
  '에잇세컨즈': 'ssfshop.com',
  '엔제리너스': 'angelinus.com',
  '엽기떡볶이': 'yupdduk.com',
  '오뚜기': 'ottogi.co.kr',
  '윌슨': 'wilson.com',
  '윌슨(국가표준)': 'wilson.com',
  '유니클로': 'uniqlo.com',
  '이디야': 'ediya.com',
  '이마트': 'emart.com',
  '임블리': 'imvely.com',
  '자라': 'zara.com',
  '커버낫': 'covernat.net',
  '커피빈': 'coffeebeankorea.com',
  '컨버스': 'converse.com',
  '컴포즈커피': 'composecoffee.com',
  '코오롱스포츠': 'kolonsport.com',
  '코오롱스포츠/디스커버리': 'discovery-expedition.com',
  '크록스': 'crocs.com',
  '탐앤탐스': 'tomntoms.com',
  '탑텐': 'topten.shinsung.co.kr',
  '투썸플레이스': 'twosome.co.kr',
  '팀홀튼': 'timhortons.com',
  '파퀴': 'paqui.com',
  '팔도': 'paldofood.co.kr',
  '폴바셋': 'paulbassett.co.kr',
  '푸마': 'puma.com',
  '프로스펙스': 'prospecs.com',
  '하림': 'harim.com',
  '할리스': 'hollys.com',
  '호카': 'hoka.com',
};
